### PR TITLE
Cleanup of the *.service files at generator; Support to re-write conserver and systemd configuration files when adding or removing an IOC

### PR DESCRIPTION
**Pull request by douglasbeniz**
Hello Wayne!

I'm proposing some changes here, I've performed some tests and they seem to be working fine, but, it's always good to test them more;

Main topics:
* Cleanup of the *.service files at generator;
* Support to re-write conserver and sustem-d configuration files when adding or removing an IOC automatically;
* It seems that '.service' files prefix name were changed from 'procserv-' to 'ioc@' in the generator, but not in manage scripts... I did it...

### CODE REVIEW

**Comment by jeonghanlee** [comment]
@douglasbeniz , I didn't check much, however, few things I would like to comment. 

- systemd is the common jargon, I would like to keep it instead of system-D 
- Each OS has the different systemd path info, it would be better to define outside python scripts.

**Comment by waynelewis** [comment]
Thanks @douglasbeniz . I will have a look at these and either get back to your or just merge the changes.

@jeonghanlee , I agree with your comment on systemd. That is the standard way of referring to it, so we should stay consistent with that.

@jeonghanlee , regarding the path location, it looks like both RedHat and Debian flavours of Linux recognise `/etc/systemd/system` as a location for the service files, and will prioritize that location over other locations. From what I can see, other locations are either used for package installed service files, or runtime-generated service files.

**Comment by jeonghanlee** [comment]
@waynelewis , from my experience, unit file (created by me) should be in the different locations in CentOS and Debian distribution. Then `systemctl enable whatever.service` will create the symbolic link to in `/etc/systemd/system/*target/whatever.service``. Both are different.  For Debian, it is ok to put unit file in `/etc/systemd/system/`. However, CentOS it doesn't work and I got the following error
```
# systemctl enable ethercat
Failed to execute operation: Access denied
```
CentOS I have to put that file `/usr/lib/systemd/system`.  I will check them more later.

**Comment by douglasbeniz** [comment]
Thanks @jeonghanlee  and @waynelewis, firstly!

I've named 'System-D' to avoid confusion (I made all the time since *systemd* and *system* are involved. I'll change the denomination, no problem.

@jeonghanlee, regarding  */etc/systemd/system*, it is defined internally as the default directory in the case the user doesn't inform anything else using *-D* parameter (look at this part in the code: '-D', '--outsysd', default=systemd_dir).

I know this is only for internal access at ESS, but I've included some details in a comment at https://confluence.esss.lu.se/display/IS/Autostart+of+IOC+-+Using+manage-procs+to+create+systemd+configuration.

**Comment by jeonghanlee** [comment]
@waynelewis , I checked the source codes, which do not have `systemctl disable/enable whatever.service` in any places.  Could you identify these options are necessary for our situations? If we don't need these options, we can use only one `/etc/systemd/system` path, even if I prefer the full command options support within systemd services.

**Comment by waynelewis** [comment]
> @waynelewis , I checked the source codes, which do not have `systemctl disable/enable whatever.service` in any places. Could you identify these options are necessary for our situations? If we don't need these options, we can use only one `/etc/systemd/system` path, even if I prefer the full command options support within systemd services.

@jeonghanlee , the scripts do not directly call `systemd enable/disable`. The `run` function in `procServUtils/generator.py` creates a symlink from the `multi-user.target.wants` directory to the IOC service file, which is effectively that `systemd enable` is doing. 

My understanding is that once the service file is created in the appropriate location, the standard `systemd` commands become available.

**Comment by jeonghanlee** [comment]
> @jeonghanlee , the scripts do not directly call `systemd enable/disable`. The `run` function in `procServUtils/generator.py` creates a symlink from the `multi-user.target.wants` directory to the IOC service file, which is effectively that `systemd enable` is doing.
> 
> My understanding is that once the service file is created in the appropriate location, the standard `systemd` commands become available.


Yes,  for Debian, the unit file is located in /etc/systemd/system. `enable` will create the symbolic link, and `disable` will delete the symbolic link in multi-user.target.wants.  However, CentOS, the unit file is located in /usr/lib/systemd/system can be linked with in multi-user.target.wants with `enable` and `disable`.  

`systemctl enable/disable` is also the standard `systemd` commands in my understanding. 

However, do you think to keep that commands are compatible with the systemd commands options is valuable for our approach? I may think, it is not necessary to keep them.  

Oh, you merged :) Ok, let's stop  this cumbersome discussion.

**Comment by waynelewis** [comment]
@jeonghanlee 
 
> Yes, for Debian, the unit file is located in /etc/systemd/system. `enable` will create the symbolic link, and `disable` will delete the symbolic link in multi-user.target.wants. However, CentOS, the unit file is located in /usr/lib/systemd/system can be linked with in multi-user.target.wants with `enable` and `disable`.

`systemctl enable/disable` is working OK on a CentOS system we are using where the unit files are in `/etc/systemd/system`:

```
[iocuser@localhost system]$ sudo systemctl enable ioc@labs-utg-p5k01.service
Created symlink from /etc/systemd/system/multi-user.target.wants/ioc@labs-utg-p5k01.service to /etc/systemd/system/ioc@labs-utg-p5k01.service.
[iocuser@localhost system]$
```

I think that the `/usr/lib/systemd/system` is for unit files that are installed by packages. It's one of the search paths for `systemd`.

> 
> `systemctl enable/disable` is also the standard `systemd` commands in my understanding.
> 
Yes, this is correct. My mistake above.

**Comment by jeonghanlee** [comment]
@waynelewis I also tested it. It works in the same way what you described. I will come back procServUtils later, because I would like to expand this tool for with / without conserver configuration. And there are some issue about python3 either. Will touch you later.

**Pull request merged**
